bookcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('books/', views.books_index, name='index'),
  path('books/<int:book_id>/', views.books_detail, name='detail'),
  path('books/<int:book_id>/add_print/', views.add_print, name='add_print')
]

main_app/models.py
from django.db import models

COVERS = (
    ('P', 'Paperback'),
    ('C', 'Case Wrap'),
    ('D', 'Dust Jacket'),
)


class Translator(models.Model):
    name = models.CharField(max_length=50)
    country = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.name} and {self.country}"
    
    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.id})
    


# Create your models here.
class Book(models.Model):
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    pages = models.IntegerField()
    translators = models.ManyToManyField(Translator)

    def __str__(self):
        return self.name




class Print(models.Model):
    date = models.DateField()
    cover = models.CharField(
        max_length=1,choices=COVERS, default=COVERS[0][0] )
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_cover_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Print

class NewPrint(ModelForm):
    class Meta:
        model = Print
        fields = ['date', 'cover']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Book, Translator
from .forms import NewPrint

# Create your views here.def

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')    

def books_index(request):
    books = Book.objects.all()
    return render(request, 'books/index.html', {'books': books})    


def books_detail(request, book_id):
    book = Book.objects.get(id=book_id)
    trans_book_no_have = Translator.objects.exclude(id__in = book.translators.all().values_list('id'))
    print_form = NewPrint()
    return render(request, 'books/book_detail.html', {'book': book, 'print_form': print_form, 'trans': trans_book_no_have})    


def add_print(request, book_id):
    form = NewPrint(request.POST)
    if form.is_valid():
        new_print = form.save(commit=False)
        new_print.book_id = book_id
        new_print.save()
    return redirect('detail', book_id=book_id)        

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About the Cat Collector</h1>
<hr />
<p>Hire the Cat Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Book Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;CatCollector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="/about">About</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserved, &copy; 2019 Cat Collector &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/books/book_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Book Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ book.name }}</span>
                <p>Author: {{ book.author }}</p>
                <p>Description: {{ book.description }}</p>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_print' book.id %}"  method="POST">
            {% csrf_token %}
            {{ print_form.as_p }}
            <input type="submit" class="btn" value="Add Print">
        </form>
    </div>

    <div class="col s6">
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Cover</th>
                </tr>
            </thead>
            <tbody>
                {% for print in book.print_set.all %}
                <tr>
                    <td>{{print.date}}</td>
                    <td>{{print.get_cover_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ book.name }}'s Translators</h3>
        {% if book.translators.count %}
        {% for trans in book.translators.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style=>{{ trans.name }}</span> {{ trans.country }}
                </span>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>No Translators :(</h5>
        {% endif %}
    </div>
    <!-- Available toys will come after this line -->
    </div>
    <!-- Available toys will come after this line -->
    <div class="col s6">
        <h3>Available Translators</h3>
        {% if trans.count %}
        {% for translator in trans.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ toy.color }}">{{ translator.name }}</span> {{ translator.country }}
                </span>
            </div>
            <div class="card-action">
                <form action="" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{Book.name}} Already Has All Translators Available</h5>
        {% endif %}
    </div>
</div>
<script>
      var dateEl = document.getElementById('id_date');
        M.Datepicker.init(dateEl, {
            format: 'yyyy-mm-dd',
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true
        });
          var selectEl = document.getElementById('id_cover');
            M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/books/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Book List</h1>

{% for book in books %}
<div class="card">
    <a href="{% url 'detail' book.id %}">
    <div class="card-content">
        <span class="card-title">{{ book.name }}</span>
        <p>Author: {{ book.author }}</p>
        <p>Description: {{ book.description }}</p>
        <p>Pages: {{ book.pages }}</p>
    </div>
    </a>
</div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Book Collector</h1>


{% endblock %}